// <auto-generated />
using System;
using GFDSystems.Vigitech.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GFDSystems.Vigitech.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210319230208_addFieldsNotificationFirebase")]
    partial class addFieldsNotificationFirebase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalNumber")
                        .IsRequired()
                        .HasColumnName("ExternalNumber")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("InternalNumber")
                        .HasColumnName("InternalNumber")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnName("Street")
                        .HasColumnType("varchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SuburbId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("SuburbId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("AspNetUserId")
                        .HasColumnType("int");

                    b.Property<string>("CURP")
                        .HasColumnName("CURP")
                        .HasColumnType("varchar(18)")
                        .HasMaxLength(18);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Sex")
                        .HasColumnName("Sex")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("CitizenId");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("Citizen");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.DeviceAssigned", b =>
                {
                    b.Property<int>("DeviceAssignedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeviceAssignedId")
                        .HasColumnType("int");

                    b.Property<int>("CarLicence")
                        .HasColumnName("CarLicence")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DateAsignation")
                        .HasColumnName("DateAsignation")
                        .HasColumnType("datetime");

                    b.Property<int>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<int>("SecurityAgentID")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("DeviceAssignedId");

                    b.HasIndex("SecurityAgentID");

                    b.HasIndex("StatusId");

                    b.ToTable("DeviceAssigned");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.HistoryDeviceAssigned", b =>
                {
                    b.Property<int>("HistoryDeviceAssignedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("HistoryDeviceAssignedId")
                        .HasColumnType("int");

                    b.Property<int>("CarLicence")
                        .HasColumnName("CarLicence")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DateAsignation")
                        .HasColumnName("DateAsignation")
                        .HasColumnType("datetime");

                    b.Property<int>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<int>("DeviceAssignedId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityAgentID")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("HistoryDeviceAssignedId");

                    b.HasIndex("DeviceAssignedId");

                    b.HasIndex("SecurityAgentID");

                    b.HasIndex("StatusId");

                    b.ToTable("HistoryDeviceAssigned");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgent", b =>
                {
                    b.Property<int>("SecurityAgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SecurityAgentId")
                        .HasColumnType("int");

                    b.Property<string>("AgentLicence")
                        .IsRequired()
                        .HasColumnName("AgentLicence")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("AspNetUserId")
                        .HasColumnType("int");

                    b.Property<string>("Corporation")
                        .IsRequired()
                        .HasColumnName("Corporation")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DateRegister")
                        .HasColumnName("DateRegister")
                        .HasColumnType("datetime");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnName("Rank")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SecurityAgentId");

                    b.HasIndex("AspNetUserId");

                    b.ToTable("SecurityAgent");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgentEmergency", b =>
                {
                    b.Property<int>("SecurityAgentEmergencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SecurityAgentEmergencyId")
                        .HasColumnType("int");

                    b.Property<int>("EmergencyAlertId")
                        .HasColumnType("int");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnName("Folio")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("PatrolNumber")
                        .IsRequired()
                        .HasColumnName("PatrolNumber")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("SecurityAgentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("Status")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("SecurityAgentEmergencyId");

                    b.HasIndex("EmergencyAlertId");

                    b.HasIndex("SecurityAgentId");

                    b.ToTable("SecurityAgentEmergency");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.StatusDevice", b =>
                {
                    b.Property<int>("StatusDeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StatusDeviceID")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("int")
                        .HasMaxLength(20);

                    b.HasKey("StatusDeviceID");

                    b.ToTable("StatusDevice");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.EmergencyAlert", b =>
                {
                    b.Property<int>("EmergencyAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmergencyAlertId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasColumnType("varchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnName("Commentary")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnName("DateRegistration")
                        .HasColumnType("datetime");

                    b.Property<string>("Latlong")
                        .IsRequired()
                        .HasColumnName("LatpLong")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PostalCode")
                        .HasColumnName("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnName("Reference")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SuburbId")
                        .HasColumnType("int");

                    b.Property<int>("TypeEmergencyId")
                        .HasColumnType("int");

                    b.Property<int>("TypeIncidenceId")
                        .HasColumnType("int");

                    b.HasKey("EmergencyAlertId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("SuburbId");

                    b.HasIndex("TypeEmergencyId");

                    b.HasIndex("TypeIncidenceId");

                    b.ToTable("EmergencyAlert");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.EmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmergencyContactId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("PhoneNumber")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Relationship")
                        .HasColumnName("Relationship")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("EmergencyContactId");

                    b.HasIndex("CitizenId");

                    b.ToTable("EmergencyContact");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.EmergencyDirectory", b =>
                {
                    b.Property<int>("EmergencyDirectoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmergencyDirectoryId")
                        .HasColumnType("int");

                    b.Property<string>("LatLong")
                        .IsRequired()
                        .HasColumnName("LatLang")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NameArea")
                        .IsRequired()
                        .HasColumnName("NameArea")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("Phone")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12);

                    b.HasKey("EmergencyDirectoryId");

                    b.ToTable("EmergencyDirectory");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.FoliosControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdUsersControl")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Prefix")
                        .HasColumnName("Prefix")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("Secuencial")
                        .HasColumnName("Secuencial")
                        .HasColumnType("int");

                    b.Property<string>("Sufix")
                        .HasColumnName("Sufix")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("Type")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("FoliosControls");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.GroupStatus", b =>
                {
                    b.Property<int>("GroupStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GroupStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("GroupStatusId");

                    b.ToTable("GroupStatus");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.GroupType", b =>
                {
                    b.Property<int>("GroupTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("GroupTypeID");

                    b.ToTable("GroupType");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alergies")
                        .HasColumnName("Alergies")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("BloodType")
                        .HasColumnName("BloodType")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("Medicines")
                        .HasColumnName("Medicines")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Suffering")
                        .HasColumnName("Suffering")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MedicalRecordId");

                    b.HasIndex("CitizenId");

                    b.ToTable("MedicalRecord");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.MobileDeviceRegistration", b =>
                {
                    b.Property<int>("MobileDeviceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CellComapny")
                        .IsRequired()
                        .HasColumnName("CellComapny")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnName("DateRegister")
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnName("DeviceId")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LatLangRegister")
                        .IsRequired()
                        .HasColumnName("LatLangRegister")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("MakeModel")
                        .HasColumnName("MakeModel")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnName("NumberPhone")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Platform")
                        .HasColumnName("Platform")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("VersionOS")
                        .HasColumnName("VersionOS")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("MobileDeviceRegistrationId");

                    b.HasIndex("CitizenId");

                    b.ToTable("MobileDeviceRegistration");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.NotificationBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NotificationBaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnName("DateRegister")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAspNetUserReceive")
                        .HasColumnName("IdAspNetUserReceive")
                        .HasColumnType("int");

                    b.Property<int>("IdAspNetUserSend")
                        .HasColumnName("IdAspNetUserSend")
                        .HasColumnType("int");

                    b.Property<string>("IdFirebaseNotification")
                        .HasColumnName("IdFirebaseNotification")
                        .HasColumnType("varchar(35)")
                        .HasMaxLength(35);

                    b.Property<string>("IdUserFirebaseReceive")
                        .IsRequired()
                        .HasColumnName("IdUserFirebaseReceive")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("IdUserFirebaseSend")
                        .IsRequired()
                        .HasColumnName("IdUserFirebaseSend")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<double>("Latitude")
                        .HasColumnName("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("LevelPriority")
                        .IsRequired()
                        .HasColumnName("LevelPriority")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24);

                    b.Property<double>("Longitude")
                        .HasColumnName("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("Message")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("Status")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("Type")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("UserNameReceive")
                        .IsRequired()
                        .HasColumnName("UserNameReceive")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserNameSend")
                        .IsRequired()
                        .HasColumnName("UserNameSend")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("NotificationBases");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<bool?>("Estatus")
                        .HasColumnName("Estatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Status", b =>
                {
                    b.Property<string>("TypeId")
                        .HasColumnName("StatusId")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("GroupStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("TypeId");

                    b.HasIndex("GroupStatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Suburb", b =>
                {
                    b.Property<int>("SuburbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("PostalCode")
                        .HasColumnName("PostalCode")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("SuburbId");

                    b.HasIndex("TownId");

                    b.ToTable("Suburb");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_system_log")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnName("action")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnName("controller")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateLog")
                        .HasColumnName("date_log")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnName("parameter")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemLog");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TownId");

                    b.HasIndex("StateId");

                    b.ToTable("Town");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Type", b =>
                {
                    b.Property<string>("TypeId")
                        .HasColumnName("TypeId")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("GroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("TypeId");

                    b.HasIndex("GroupTypeId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.TypeEmergency", b =>
                {
                    b.Property<int>("TypeEmergencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TypeEmergencyId")
                        .HasColumnType("int");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnName("Acronym")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool?>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TypeEmergencyId");

                    b.ToTable("TypeEmergency");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.TypeIncidence", b =>
                {
                    b.Property<int>("TypeIncidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TypeIncidenceId")
                        .HasColumnType("int");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnName("Acronym")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool?>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TypeIncidenceId");

                    b.ToTable("TypeIncidence");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Usuarios.MobileDeviceRegistrationTemp", b =>
                {
                    b.Property<int>("MobileDeviceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnName("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CellComapny")
                        .IsRequired()
                        .HasColumnName("CellComapny")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("DateRegister")
                        .HasColumnName("DateRegister")
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnName("DeviceId")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<bool>("IsCompleteRegister")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LatLangRegister")
                        .IsRequired()
                        .HasColumnName("LatLangRegister")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("MakeModel")
                        .HasColumnName("MakeModel")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnName("NumberPhone")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Platform")
                        .HasColumnName("Platform")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("VersionOS")
                        .HasColumnName("VersionOS")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("MobileDeviceRegistrationId");

                    b.ToTable("MobileDeviceRegistrationTemp");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Models.ApiKeyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ApiKeyUserId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnName("Key")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("ApiKeyUsers");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasColumnName("area")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("AuthValidationCode")
                        .HasColumnName("authValidationCode")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirebaseId")
                        .HasColumnName("firebaseId")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FirebasePassword")
                        .HasColumnName("firebasePassword")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnName("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnName("middleName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnName("profilePicture")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Address", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Citizen", "citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Suburb", "suburb")
                        .WithMany()
                        .HasForeignKey("SuburbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Citizen", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", "appUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.DeviceAssigned", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgent", "SecurityAgent")
                        .WithMany()
                        .HasForeignKey("SecurityAgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.StatusDevice", "StatusDevice")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.HistoryDeviceAssigned", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.DeviceAssigned", "DeviceAssigned")
                        .WithMany()
                        .HasForeignKey("DeviceAssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgent", "SecurityAgent")
                        .WithMany()
                        .HasForeignKey("SecurityAgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.StatusDevice", "StatusDevice")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgent", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", "appUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgentEmergency", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.EmergencyAlert", "emergencyAlert")
                        .WithMany()
                        .HasForeignKey("EmergencyAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.ControlEmergencias.SecurityAgent", "securityAgent")
                        .WithMany()
                        .HasForeignKey("SecurityAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.EmergencyAlert", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Citizen", "citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Suburb", "suburb")
                        .WithMany()
                        .HasForeignKey("SuburbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.TypeEmergency", "typeEmergency")
                        .WithMany()
                        .HasForeignKey("TypeEmergencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.TypeIncidence", "typeIncidence")
                        .WithMany()
                        .HasForeignKey("TypeIncidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.EmergencyContact", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Citizen", "citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.MedicalRecord", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Citizen", "citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.MobileDeviceRegistration", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Citizen", "citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Status", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.GroupStatus", "GroupStatus")
                        .WithMany()
                        .HasForeignKey("GroupStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Suburb", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.Town", "town")
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Town", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.State", "state")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Entities.Type", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Entities.GroupType", "groupType")
                        .WithMany()
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFDSystems.Vigitech.DAL.Models.ApiKeyUser", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", "User")
                        .WithOne("ApiKeyUser")
                        .HasForeignKey("GFDSystems.Vigitech.DAL.Models.ApiKeyUser", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GFDSystems.Vigitech.DAL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
